// THIS FILE IS AUTO-GENERATED by site/scripts/gen-types.mjs
// DO NOT EDIT BY HAND — changes will be overwritten on next build.
// Source: schema/*.schema.json

export interface RMEPaperEntry {
  /**
   * arXiv id (e.g. 2210.12345) or kebab-case slug; must equal filename stem
   */
  id: string;
  title: string;
  /**
   * @minItems 1
   */
  authors: [string, ...string[]];
  year: number;
  venue?: string;
  abstract?: string;
  /**
   * One-sentence human summary
   */
  tldr?: string;
  links?: {
    arxiv?: string;
    pdf?: string;
    code?: string;
    project_page?: string;
    doi?: string;
  };
  subfield: 'REM' | 'spectrum-cartography' | 'pathloss-prediction' | 'CKM';
  method_family: 'interpolation' | 'model-based' | 'learning-based' | 'application';
  method_detail?: (
    | 'Kriging'
    | 'IDW'
    | 'matrix-completion'
    | 'ray-tracing'
    | 'CNN'
    | 'GAN'
    | 'Transformer'
    | 'INR'
    | 'Diffusion'
    | 'GNN'
    | 'RNN'
    | 'autoencoder'
    | 'Gaussian-process'
    | 'other'
  )[];
  /**
   * @minItems 1
   */
  task: [
    (
      | 'signal-strength-estimation'
      | 'coverage-prediction'
      | 'spectrum-occupancy'
      | 'pathloss-prediction'
      | 'channel-gain-prediction'
      | 'spectrum-cartography'
      | 'REM-construction'
      | 'other'
    ),
    ...(
      | 'signal-strength-estimation'
      | 'coverage-prediction'
      | 'spectrum-occupancy'
      | 'pathloss-prediction'
      | 'channel-gain-prediction'
      | 'spectrum-cartography'
      | 'REM-construction'
      | 'other'
    )[]
  ];
  input_modality: 'sparse-measurements' | 'environment-map' | 'both';
  environment: 'indoor' | 'outdoor' | 'both';
  dimensionality: '2D' | '3D';
  supervision: 'supervised' | 'self-supervised' | 'unsupervised' | 'semi-supervised' | 'n/a';
  /**
   * dataset ids; each must exist in data/datasets.yml (checked by validate.py)
   */
  datasets?: string[];
  /**
   * Semantic Scholar count; refreshed periodically (v2 job)
   */
  citations?: number;
  is_milestone?: boolean;
  tags?: string[];
  added_date: string;
}

export interface RMEDatasetCatalog {
  datasets: {
    /**
     * kebab-case dataset identifier; referenced by data/papers/*.yml datasets[]
     */
    id: string;
    /**
     * Human-readable dataset name
     */
    name: string;
    /**
     * One- or two-sentence description of the dataset
     */
    description: string;
    /**
     * Canonical URL for the dataset (homepage, repo, or paper)
     */
    link: string;
    /**
     * paper ids (data/papers/*.yml stems) that use this dataset
     */
    papers_using?: string[];
    /**
     * Optional leaderboard rows: a paper's reported metric value on this dataset
     */
    benchmark?: {
      /**
       * paper id of the reporting paper
       */
      paper_id: string;
      /**
       * metric name (e.g. RMSE, NMSE, SSIM)
       */
      metric: string;
      /**
       * reported metric value
       */
      value: number;
    }[];
  }[];
}

export interface RMETaxonomyTree {
  taxonomy: Node[];
}
export interface Node {
  /**
   * kebab-case node identifier, unique within the tree
   */
  id: string;
  /**
   * Human-readable node label
   */
  label: string;
  /**
   * Optional one-line explanation of the node
   */
  description?: string;
  /**
   * Optional child nodes; recursive
   */
  children?: Node[];
}

export interface RMEReadingPath {
  steps: {
    /**
     * 1-based position of this step in the reading path
     */
    order: number;
    /**
     * paper id (data/papers/*.yml stem) to read at this step
     */
    paper_id: string;
    /**
     * Rationale: why a newcomer should read this paper at this point
     */
    why: string;
  }[];
}
